name: CI
on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v1
        with:
          java-version: 16
      - name: Build
        run: ./gradlew build
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.PRIVATEKEY }}
          known_hosts: 'placeholder'
      - name: Add known hosts
        run: ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts
      - name: Sanity check
        run: echo ${{ secrets.PRIVATEKEY }}
      - name: Sanity check 2
        run: echo ${{ secrets.HOST }}
      - name: Sanity check 3
        run: echo ${{ secrets.USER }}
      - name: Deploy artifact
        run: rsync -avz ./build/libs/sysbot-*-all.jar ${{ secrets.USER }}@${{ secrets.HOST }}:/root/sysbot-prod/sysbot.jar
      - name: Run remote deploy script
        run: ssh ${{ secrets.USER }}@${{ secrets.HOST }} cd /root/sysbot-prod && ./deploy.sh