name: CI
on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v1
        with:
          java-version: 16
      - name: Build
        run: ./gradlew build
      - name: Install sshpass
        run: sudo apt install sshpass
      - name: Sanity check
        run: cd build ; ls -a ; cd libs ; ls -a ; cd ../..
      - name: Deploy artifact
        run: sshpass -p "${{ secrets.PASSWORD }}" scp -o StrictHostKeyChecking=no build/libs/sysbot-*-all.jar ${{ secrets.USER }}@${{ secrets.HOST }}:/root/sysbot-prod/sysbot.jar
      - name: Run remote deploy script
        run: sshpass -p "${{ secrets.PASSWORD }}" ssh ${{ secrets.USER }}@${{ secrets.HOST }} cd /root/sysbot-prod && ./deploy.sh